### ISSUE TITLE
PHP errors Uninitialized string offset and Illegal string offset 'RESULT' in TimeMachine module

### ISSUE THREAD

**Issue by precursorca** [munkireport/timemachine#6] opened 2020-09-30 13:01 UTC
I see a lot of this in my web errors log
```
[php7:notice] [pid 92917] [client x.x.x.x:64855] PHP Notice:  Uninitialized string offset: 0 in /Users/Shared/munkireport-php/vendor/munkireport/timemachine/timemachine_model.php on line 290
[php7:warn] [pid 92917] [client x.x.x.x:64855] PHP Warning:  Illegal string offset 'RESULT' in /Users/Shared/munkireport-php/vendor/munkireport/timemachine/timemachine_model.php on line 290
[php7:notice] [pid 92917] [client x.x.x.x:64855] PHP Notice:  Uninitialized string offset: 0 in /Users/Shared/munkireport-php/vendor/munkireport/timemachine/timemachine_model.php on line 290
[php7:notice] [pid 92917] [client x.x.x.x:64855] PHP Notice:  Uninitialized string offset: 0 in /Users/Shared/munkireport-php/vendor/munkireport/timemachine/timemachine_model.php on line 294
[php7:warn] [pid 92917] [client x.x.x.x:64855] PHP Warning:  Illegal string offset 'RESULT' in /Users/Shared/munkireport-php/vendor/munkireport/timemachine/timemachine_model.php on line 294
[php7:notice] [pid 92917] [client x.x.x.x:64855] PHP Notice:  Uninitialized string offset: 0 in /Users/Shared/munkireport-php/vendor/munkireport/timemachine/timemachine_model.php on line 294
```

**Comment by tuxudo** [comment] 2020-10-25 00:57
Duplicate of issue #5

**Closed as completed by tuxudo** 2020-10-25 00:57 UTC
